### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by dbaeyens** [dbaeyens/crittertest#1]
<a href="https://app.crittercism.com/developers/crash-details/4879b6b38d025790d185368c4b589a5d4f48e4c012d445e2beff4d13"> View Crash Report on Crittercism </a> 

 Reported by: Daniel Baeyens Status: Unresolved

This Crash occured 1 times for 1 users

0 java.lang.RuntimeException: This is a crash
1 	at com.example.mycrittercismtestapplication.MainActivity$1.onClick(MainActivity.java:32)
2 	at android.view.View.performClick(View.java:5198)
3 	at android.view.View$PerformClick.run(View.java:21147)
4 	at android.os.Handler.handleCallback(Handler.java:739)
5 	at android.os.Handler.dispatchMessage(Handler.java:95)
6 	at android.os.Looper.loop(Looper.java:148)
7 	at android.app.ActivityThread.main(ActivityThread.java:5417)
8 	at java.lang.reflect.Method.invoke(Native Method)
9 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by dbaeyens** [comment]
tal tal cual tal
